<td class="item">
    <input type="hidden" name="entry_id[{{queue}}][]" value="{{id}}">
    <img src="{{thumb}}">
    <a href="/edit?id={{id}}">
        <span class="entry-title">{{title}}</span>
    </a>
    <div class="clearfix"></div>
    {{queueLabel}}<br />
    {{tags}}
    <div class="clearfix"></div>
    <a href="\edit?id={{id}}">Edit</a>&nbsp;|&nbsp;
    <a href="\delete?id={{id}}">Delete</a>
</td>