<div class="col-xs-6 entry-item">
    <p class="entry-title">
        <a href="{{url}}">{{title}}</a>
    </p>
    <div class="entry-image hidden-xs">
        <a href="{{url}}" title="{{title}}">
            <img class="lazy" data-original="{{mobile_thumb}}" alt="{{title}}">
        </a>
    </div>
    <div class="entry-images visible-xs">
        <div class="image-box col-xs-12 col-sm-4">
            <a href="{{url}}" class="image col-xs-6" title="{{title}}">
                <img class="lazy" data-original="{{mobile_1_thumb}}" alt="{{title}}" >
            </a>
            <a href="{{url}}" class="image col-xs-6" title="{{title}}">
                <img class="lazy" data-original="{{mobile_2_thumb}}" alt="{{title}}" >
            </a>
        </div>
    </div>
    <p class="entry-date">{{publishedAt_short}}</p>
</div>