{{include head.phtml}}
<body>
	<div class="wrapper-outer">
    {{include header.phtml}}
		<div class="wrapper-inner">
            {{include sidebar.phtml}}
			<div class="content">
				<div class="content-head"></div>
				<div class="ad-top">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x15, created 12/30/09 */
					google_ad_slot = "7425641670";
					google_ad_width = 728;
					google_ad_height = 15;
					//-->
					</script>
					<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
				</div>
        {{content}}
				<div class="ad-bottom">
					<script type="text/javascript"><!--
					google_ad_client = "pub-9622612302631221";
					/* 728x90, created 12/30/09 */
					google_ad_slot = "7751544997";
					google_ad_width = 728;
					google_ad_height = 90;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
		</div>
	</div>
{{include footer.phtml}}
