<?php
/**
 * @author		Dennis Rogers
 * @address		www.drogers.net
 */
?>

<div class="entry-view">
	<h2 class="entry-title"><a href="{{entry url}}" title="{{entry title}}">{{entry title}}</a></h2>
	<p class="entry-date">{{entry published_at}}</p>
	<a href="{{entry url_path}}" class="entry-preview-image" title="{{entry title}}">
        <img src="{{entry preview}}" alt="{{entry title}}"/>
    </a>
	<p class="entry-content">{{entry content}}</p>
</div>