<!-- Entry ID {{entry id}} -->
<div class="entry-view">
    <div class="clearfix">
        <p class="pull-left">{{entry prev_link}}</p>
        <p class="pull-right text-right">{{entry next_link}}</p>
    </div>
	<h2 class="entry-title">{{entry title}}</h2>
	<p class="entry-date">{{entry published_at}}</p>
	<a href="{{entry first_image}}" class="entry-preview-image" title="{{entry title}}">
        <img src="{{entry first_image}}" alt="{{entry title}}"/>
        <span class="visible-xs">Desktop</span>
    </a>
	<p class="entry-content">{{entry content}}</p>
	<div class="row-fluid">
<!--
    	<div class="entry-versions col-sm-5 col-xs-12">
    		<h4>Versions</h4>
    		<ul>
    		{{entry kinds}}
    		</ul>
    	</div>
-->
    	<div class="entry-tags pull-left">
            {{entry tags}}
    	</div>
    	<div class="social-media pull-right">
    		<h4>Share</h4>
            <ul>
                <li><a class="facebook" href="https://www.facebook.com/sharer/sharer.php?u={{entry url}}&title={{entry title}}">Share</a></li>
                <li><a class="twitter" href="http://twitter.com/intent/tweet?url={{entry url}}&text={{entry title}}+-+{{entry preview}}&hashtags=wallpaper,background">Tweet</a></li>
                <li><a class="pinterest" href="http://pinterest.com/pin/create/bookmarklet/?media={{entry preview}}&url={{entry url}}&is_video=false&description={{entry title}}">Pin</a></li>
            </ul>
    	</div>
	</div>
	<div class="clearfix"></div>
    <h4>Wallpaper Types</h4>
	<div class="entry-images">
        {{entry image_gallery}}	
	</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = 'spartacuswallpaper';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    <div class="row">
        <div class="prev col-xs-6 col-sm-5 col-md-4">
            {{entry prev}}
        </div>
        <div class="next col-xs-6 col-sm-5 col-md-4 pull-right text-right">
            {{entry next}}
        </div>
    </div>
</div>


