<div class="entry-view">
	<h2 class="entry-title"><a href="{{baseurl}}{{entry url_path}}" title="{{entry title}}">{{entry title}}</a></h2>
	<p class="entry-date">{{entry published_at}}</p>
	<a href="{{baseurl}}{{entry url_path}}" class="entry-preview-image {{entry mobile}}" title="{{entry title}}">
        <img src="{{entry preview}}" alt="{{entry title}}"/>
    </a>
    {{entry mobile_images}}
	<p class="entry-content">{{entry content}}</p>
</div>