<div data-role="content" style="max-width:400px">
    <form enctype="application/x-www-form-urlencoded" method="post">
        <h2>Please sign in</h2>
        <dl>
            <dt>
                <label for="inputPassword">Password</label>
            </dt>
            <dd>
                <input type="password" id="password" name="password" placeholder="Password" required autofocus>
            </dd>
        </dl>
        <button type="submit" class="btn-lg">Sign in</button>
    </form>
</div>