<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
{{%page/head%}}
<body>
	<div class="container-fluid">
    {{%page/header%}}
		<div class="row-fluid">
            <div class="col-md-3" id="sidebar">
                {{%page/sidebar%}}
            </div>
            <div class="col-md-9" id="main">
                <h2 class="content-title">{{content_title}}</h2>
                {{content}}
                <nav class="pager">
                    {{pager}}
                </nav>
            </div>
		</div>
    {{%page/footer%}}
    </div>
</body>
