<p class="section-head">Wallpapers by Type</p>
<ul class="kinds">
    {{kinds}}
</ul>
<ul class="social-contact">
    <li class="twitter"><a href="https://twitter.com/spartacuswalls">@spartacuswalls</a></li>
    <li class="facebook"><a href="http://www.facebook.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
    <li class="pinterest"><a href="http://www.pinterest.com/spartacuswalls/">spartacuswalls</a></li>
</ul>
<p class="section-head">Calendar Series</p>
<div class="row calendar">
{{calendar}}
</div>
<p class="section-head">Wallpapers by Year</p>
<ul class="years">
    {{tag_years}}
</ul>
<p class="section-head">Top 10 Ladies</p>
<div class="row tops">
{{tag_10}}
</div>
<ul class="social-contact">
    <li class="twitter"><a href="https://twitter.com/spartacuswalls">@spartacuswalls</a></li>
    <li class="facebook"><a href="http://www.facebook.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
    <li class="pinterest"><a href="http://www.pinterest.com/spartacuswalls/">spartacuswalls</a></li>
</ul>
