<h2>{{contentTitle}}</h2>
<a href="/">Back</a>
<form action="/tag/save" method="post">
    <div class="tags items-grid">
        {{items}}
    </div>
    <dt id="tags-label"><label for="tags" class="required">tags:</label></dt>
    <dd id="tags-element">
        <textarea class="tags" name="tags" id="tags" cols="40" rows="2"></textarea>
    </dd>
    <button type="submit"><span>Add Tag</span></button>
</form>