<!-- Entry ID {{entry id}} -->
<div class="entry-view entry-page" vocab="http://schema.org/" typeof="CreativeWorkSeries">
    <div class="hidden">
        <span property="author" typeof="Thing">
            <span property="name">Spartacus Wallpaper</span>
            <span property="url">http://spartacuswallpaper.com/about</span>
        </span>
        <span property="contentRating">MPAA PG-13</span>
        <span property="thumbnailUrl">{{entry preview}}</span>
    </div>
    <div class="clearfix">
        <p class="pull-left">{{entry prev_link}}</p>
        <p class="pull-right text-right">{{entry next_link}}</p>
    </div>
    <div class="col-sm-9">
        <h2 class="entry-title" property="name">{{entry title}}</h2>
        <p class="entry-date" property="datePublished">{{entry published_at}}</p>
        <a href="{{entry first_image}}" class="entry-preview-image" title="{{entry title}}">
            <img class="lazy" data-original="{{entry preview}}" alt="{{entry title}}"/>
            <span class="visible-xs">Desktop</span>
        </a>
    </div>
    <div class="col-sm-3">
        <div class="entry-tags col-xs-6 col-sm-12">
            {{entry tags}}
        </div>
        <div class="social-media col-xs-6 col-sm-12">
            <strong>Share</strong>
            <ul>
                <li><a class="facebook" href="javascript:share();">Share</a></li>
                <li><a class="twitter" href="http://twitter.com/intent/tweet?url={{entry url}}&text={{entry title}}+-+{{entry preview}}&hashtags=wallpaper,background">Tweet</a></li>
                <li><a class="pinterest" href="http://pinterest.com/pin/create/bookmarklet/?media={{entry preview}}&url={{entry url}}&is_video=false&description={{entry title}}">Pin</a></li>
            </ul>
        </div>
    </div>
	<div class="entry-content clearfix">{{entry content}}</div>
    <strong>Wallpaper Types</strong>
	<div class="entry-images">
        {{entry image_gallery}}	
	</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = 'spartacuswallpaper';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    <div class="row">
        <div class="prev col-xs-6 col-sm-5 col-md-4">
            {{entry prev}}
        </div>
        <div class="next col-xs-6 col-sm-5 col-md-4 pull-right text-right">
            {{entry next}}
        </div>
    </div>
</div>


