{{entry_first}}
{{entry_first_mobile}}
	<div class="ad-middle">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Content Top -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-9622612302631221"
             data-ad-slot="8363371851"
             data-ad-format="auto"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
	</div>
{{entries}}