<div class="entry-view">
    <h2 class="entry-title"><a href="{{url}}" title="{{title}}">{{title}}</a></h2>
    <p class="entry-date">{{publishedAt}}</p>
    <a href="{{url}}" class="entry-preview-image" title="{{title}}">
        <img class="lazy" data-original="{{preview}}" alt="{{title}}"/>
    </a>
    <div class="row-fluid">
        <div class="entry-tags">
            {{tags}}
        </div>
    </div>
    <div class="entry-content">{{note}}</div>
</div>