<div class="col-md-12 col-sm-4 col-xs-6">
    <p class="entry-title"><a href="{{url}}">{{title}}</a></p>
    <div class="entry-image hidden-xs">
        <a href="{{url}}" title="{{title}}">
            <img class="lazy" data-original="{{thumb}}" alt="{{title}}" style="display: inline;" />
        </a>
    </div>
    <div class="entry-images visible-xs">
        <div class="image-box col-xs-12 col-sm-4">
            <a href="{{url}}" class="image col-xs-6" title="{{title}}">
                <img class="lazy" data-original="{{mobile_1}}" alt="{{title}}" />
            </a>
            <a href="{{url}}" class="image col-xs-6" title="{{title}}">
                <img class="lazy" data-original="{{mobile_2}}" alt="{{title}}" />
            </a>
        </div>
    </div>
    <p class="entry-date">{{published_at}}</p>
</div>