<td class="item live toggle">
    <div class="entry-date">{{publishedAt_short}}</div>
    <img src="{{thumb}}">
    <a href="/entry/edit?id={{id}}">
        <span class="entry-title">{{title}}</span>
    </a>
    <div class="clearfix"></div>
    {{queueLabel}}<br />
    {{tags}}
    <div class="clearfix"></div>
    <a href="{{url}}">View</a>&nbsp;|&nbsp;
    <a href="/entry/edit?id={{id}}">Edit</a>&nbsp;|&nbsp;
    <a href="/entry/delete?id={{id}}">Delete</a>
</td>