<form id="calendar" action="\queue\reorder" method="post">
    <table id="queue" class="queue">
        <thead>
            <tr>
                <td>Su</td>
                <td>Mo</td>
                <td>Tu</td>
                <td>We</td>
                <td>Th</td>
                <td>Fr</td>
                <td>Sa</td>
            </tr>
        </thead>
        <tbody>
        {{rows}}
        </tbody>
    </table>
    <button type="submit" class="btn-lg"><span>Save</span></button>
</form>