<!-- Entry ID {{id}} -->
<div class="entry-view entry-page" vocab="http://schema.org/" typeof="CreativeWorkSeries">
    <div class="hidden">
        <span property="author" typeof="Thing">
            <span property="name">Spartacus Wallpaper</span>
            <span property="url">http://spartacuswallpaper.com/about</span>
        </span>
        <span property="contentRating">MPAA PG-13</span>
        <span property="thumbnailUrl">{{preview}}</span>
    </div>
    <div class="row">
        <p class="pull-left">{{prevLink}}</p>
        <p class="pull-right text-right">{{nextLink}}</p>
    </div>
    <div class="row">
        <div class="col-sm-9">
            <h2 class="entry-title" property="name">{{title}}</h2>
            <p class="entry-date" property="datePublished">{{publishedAt}}</p>
            <a href="{{mainImage}}" class="entry-preview-image" title="{{title}}">
                <img class="lazy" data-original="{{preview}}" alt="{{title}}"/>
                <span class="visible-xs">Desktop</span>
            </a>
        </div>
        <div class="col-sm-3">
            <div class="entry-tags col-xs-6 col-sm-12">
                {{tags}}
            </div>
            <div class="social-media col-xs-6 col-sm-12">
                <strong>Share</strong>
                <ul>
                    <li><a class="facebook" href="javascript:share();">Share</a></li>
                    <li><a class="twitter" href="http://twitter.com/intent/tweet?url={{url}}&text={{title}}+-+{{preview}}&hashtags=wallpaper,background">Tweet</a></li>
                    <li><a class="pinterest" href="http://pinterest.com/pin/create/bookmarklet/?media={{preview}}&url={{url}}&is_video=false&description={{title}}">Pin</a></li>
                </ul>
            </div>
        </div>
    </div>
	<div class="entry-content row">{{note}}</div>
    <strong>Wallpaper Types</strong>
	<div class="entry-images">
        <div class="desktop hidden-xs">
            {{desktopImages}}
        </div>
        <div class="mobile text-center visible-xs">No mobile sizes here, <a onclick="jQuery('.desktop.hidden-xs').removeClass('hidden-xs');jQuery('.mobile').hide();">show desktop sizes</a>?</div>
	</div>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = 'spartacuswallpaper';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    <div class="row">
        <div class="prev col-xs-6 col-sm-5 col-md-4">
            {{prev}}
        </div>
        <div class="next col-xs-6 col-sm-5 col-md-4 pull-right text-right">
            {{next}}
        </div>
    </div>
</div>


