<a property="hasPart" typeof="ImageObject" href="{{url}}" class="image" title="{{title}}" data-ratio="{{ratio}}">
    <meta property="url" content="{{url}}">
    <meta property="width" content="{{width}} px">
    <meta property="height" content="{{height}} px">
    <img property="thumbnailUrl" class="lazy" data-original="{{thumb}}" alt="{{title}}">
    <span class="caption" property="caption" content="{{title}} - {{kind}}">{{kind}}</span>
</a>

