<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{head}}
    <title>{{title}}Desktop Backgrounds | Mobile Home Screens | Spartacus Wallpaper</title>
    <meta name="description" content="{{meta_description}}">
    <link href="https://fonts.googleapis.com/css?family=Courgette|Patua+One" rel="stylesheet">
    <link href="{{baseurl}}css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="{{baseurl}}css/custom.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="{{baseurl}}css/banner.css" media="screen" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="/favicon.ico">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="{{baseurl}}js/jquery.lazyload.js"></script>
    <script src="{{baseurl}}js/custom.js"></script>
    <script src="{{baseurl}}js/banner.js"></script>
    <script src="{{baseurl}}js/ad.js"></script>
    <script type="text/javascript">
    //<![CDATA[
    	jQuery(document).ready(function(){
        	if(window.getComputedStyle == undefined || window.getComputedStyle(document.body).backgroundBlendMode == undefined)
        		jQuery('.header-banner.banner-border').css('background-image', 'none');
        });
        function share() {
            var width = 626;
            var height = 436;
            var yourPageToShare = location.href;
            var sharerUrl = 'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(yourPageToShare);
            var l = window.screenX + (window.outerWidth - width) / 2;
            var t = window.screenY + (window.outerHeight - height) / 2;
            var winProps = ['width='+width,'height='+height,'left='+l,'top='+t,'status=no','resizable=yes','toolbar=no','menubar=no','scrollbars=yes'].join(',');
            var win = window.open(sharerUrl, 'fbShareWin', winProps);
        }
    //]]>
    </script>
</head>
