<div class="ad">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Content Sidebar -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-9622612302631221"
         data-ad-slot="8884749054"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>   
</div>
<div class="random-entries visible-md">
    {{side_more}}
</div>
<div class="ad long">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Content Sidebar -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-9622612302631221"
         data-ad-slot="8884749054"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>   
</div>
