<div class="sidebar">
	<div class="sidebar-head"></div>
	<p class="section-head">Wallpapers by Type:</p>
	<ul>
    {{kinds}}
	</ul>
	<p class="section-head">Wallpapers by Year:</p>
	<ul class="years">
    {{tag_years}}
	</ul>
	<p class="section-head">Top 20 Names:</p>
	<ul>
    {{tag_20}}
	</ul>
  <ul class="social-contact">
      <li class="twitter"><a href="https://twitter.com/spartacuswalls">@spartacuswalls</a></li>
      <li class="facebook"><a href="http://www.facebook.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
      <li class="tapiture"><a href="http://tapiture.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
      <li class="pinterest"><a href="http://www.pinterest.com/spartacuswalls/">spartacuswalls</a></li>
  </ul>
</div>
