<div class="sidebar">
	<div class="sidebar-head"></div>
	<p class="section-head">Wallpapers:</p>
	<ul>
    {{kinds}}
	</ul>
	<p class="section-head">Archive by Year:</p>
	<ul class="years">
    {{tag_years}}
	</ul>
	<p class="section-head">Top 20:</p>
	<ul>
    {{tag_20}}
	</ul>
  <ul class="social-contact">
      <li class="twitter"><a href="https://twitter.com/spartacuswalls">@spartacuswalls</a></li>
      <li class="facebook"><a href="http://www.facebook.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
      <li class="tapiture"><a href="http://tapiture.com/spartacuswallpaper">Spartacus Wallpaper</a></li>
      <li class="pinterest"><a href="http://www.pinterest.com/spartacuswalls/">spartacuswalls</a></li>
  </ul>
	<div class="ad-sidebar">
		<script type="text/javascript"><!--
		google_ad_client = "pub-9622612302631221";
		/* 120x600, created 12/14/09 */
		google_ad_slot = "6772196842";
		google_ad_width = 140;
		google_ad_height = 600;
		//-->
		</script>
		<script type="text/javascript"
		src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>
	</div>
</div>
