<?php
/**
 * @author 	dennis
 * @site 	www.spartacuswallpaper.com
 */
 ?>
<h2>About</h2>
<div class="std">
<p>Not too much to say, I'm just a guy who likes to play with photoshop, and appreciates attractive women.</p>

<p>I've been running this site in various forms since <a href="/tag/2000/">2000</a>. It began as straight html manually edited and ftp'd to an add-supported webhost. For awhile it was on blogger from around, and then wordpress. In 2012 I replaced wordpress with a web app I built to run the site on PHP, and in 2014 I built the current iteration, which uses PHP to generate static pages and cached preview images.</p>

<p>During the wordpress time I realized I could upload the wallpaper and set the post date in the future. I've run the site that way ever since, keeping a queue of images sometimes a month or more in advance of the posting schedule. The current schedule is Monday, Thursday, Saturday, and a <a href="/tag/calendar">calendar</a> series that updates on the first of every month.</p>

<p>The details of how I publish the site have changed over the years, as has the methods I use to find images to work from, and my photoshop techniques. (Seriously, the first year or so of works are not great) But I enjoy making them, and I hope you enjoy seeing them. I enjoy any kind of feedback from my visitors, so please feel free to comment on any of my postings.</p>

<p>~ Spartacus</p>
</div>