<div class="ad">
    <!-- Content Sidebar -->
    <script type="text/javascript">
        ( function() {
            var width = jQuery('#sidebar .ad').width();
            if(width < 300) width = 300;
            if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
            var unit = {"calltype":"async[2]","publisher":"spartacuswallpaper","width":width,"height":472,"sid":"Chitika Default"};
            var placement_id = window.CHITIKA.units.length;
            window.CHITIKA.units.push(unit);
            document.write('<div id="chitikaAdBlock-' + placement_id + '"></div>');
        }());
    </script>
</div>
<div class="random-entries visible-md">
    {{side_more}}
</div>
<div class="ad long">
    <!-- Content Sidebar -->
    <script type="text/javascript">
        ( function() {
            var width = jQuery('#sidebar .ad').width();
            if(width < 300) width = 300;
            if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
            var unit = {"calltype":"async[2]","publisher":"spartacuswallpaper","width":width,"height":472,"sid":"Chitika Default"};
            var placement_id = window.CHITIKA.units.length;
            window.CHITIKA.units.push(unit);
            document.write('<div id="chitikaAdBlock-' + placement_id + '"></div>');
        }());
    </script>
</div>
