<div class="ad top">
    <!-- Content Top -->
    <script type="text/javascript">
        ( function() {
            var width = jQuery('.ad.top').width();
            if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
            var unit = {"calltype":"async[2]","publisher":"spartacuswallpaper","width":width,"height":90,"sid":"Chitika Default"};
            var placement_id = window.CHITIKA.units.length;
            window.CHITIKA.units.push(unit);
            document.write('<div id="chitikaAdBlock-' + placement_id + '"></div>');
        }());
    </script>
</div>