<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
{{%head%}}
<body>
	<div class="container-fluid">
    {{%header%}}
		<div class="row-fluid">
            <div class="col-md-3" id="sidebar">
                {{%sidebar%}}
                {{%ad/sidebar%}}
            </div>
            <div class="col-md-9" id="main">
                <div class="ad top">
                    <!-- Content Top -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9622612302631221"
                         data-ad-slot="8363371851"
                         data-ad-format="auto"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                </div>
                <h2 class="content-title">{{content_title}}</h2>
                {{content}}
                <nav class="pager">
                    {{pager}}
                </nav>
                {{%ad/bottom%}}
                <div class="random-entries entry-grid row hidden-xs">
                    {{content_more}}
                </div>
            </div>
		</div>
    {{%footer%}}
    </div>
</body>
