<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
{{%head%}}
<body>
	<div class="container-fluid">
    {{%header%}}
		<div class="row-fluid">
            <div class="col-md-3" id="sidebar">
                {{%sidebar%}}
                {{%ad/sidebar%}}
            </div>
            <div class="col-md-9" id="main">
                {{%ad/top%}}
                {{content}}
                {{%ad/bottom%}}
                <div class="random-entries entry-grid row hidden-xs">
                    {{content_more}}
                </div>
            </div>
		</div>
    {{%footer%}}
    </div>
</body>
