<!DOCTYPE html>
<html xmlns:fb="http://ogp.me/ns/fb#">
{{%head%}}
<body>
	<div class="container-fluid">
    {{%header%}}
		<div class="row-fluid">
            <div class="col-md-3" id="sidebar">
                {{%sidebar%}}
                {{%ad/sidebar%}}
            </div>
            <div class="col-md-9" id="main">
                {{%ad/top%}}
                <h2 class="content-title">{{contentTitle}}</h2>
                <div class="row entry-grid">
                    {{content}}
                </div>
                {{%ad/bottom%}}
            </div>
		</div>
    {{%footer%}}
    </div>
</body>
